- name: Update Apt Package Cache
  ansible.builtin.apt:
    update_cache: true

- name: Import PostgreSQL GPG Key
  ansible.builtin.get_url:
    url: "{{ psql_url }}"
    dest: /tmp/ACCC4CF8.asc
    mode: '644'
  changed_when: false

- name: Add PostgreSQL GPG Key
  ansible.builtin.apt_key:
    keyring: "{{ psql_gpg_keyring }}"
    id: ACCC4CF8
    url: "{{ psql_url }}"

- name: Add PostgreSQL Repository
  ansible.builtin.lineinfile:
    path: "/etc/apt/sources.list.d/pgdg.list"
    line: "deb https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    create: true
    mode: '644'

- name: Update Apt Package Cache
  ansible.builtin.apt:
    update_cache: true

- name: Install PostgreSQL
  ansible.builtin.apt:
    name: "postgresql-{{ postgresql_version }}"
    state: present

- name: restart postgresql
  ansible.builtin.systemd:
    name: "{{ postgresql_service }}"
    state: restarted
